# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Michael Gardner, A Bit of Help, Inc.

linters:
  enable:
    - errcheck       # Check error handling
    - gofmt          # Format code
    - goimports      # Organize imports
    - govet          # Examine Go source code
    - staticcheck    # Advanced static analysis
    - gosec          # Security issues
    - ineffassign    # Detect ineffectual assignments
    - unused         # Find unused code
    - misspell       # Spelling errors
    - revive         # Fast, configurable linter
    - gosimple       # Simplify code
    - typecheck      # Type check code

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
